version: "3.9"
services:
  server:
    networks:
      power-net:
        ipv4_address: 10.5.0.5
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "8092:8092"
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
  client:
    depends_on:
      server:
        condition: service_started
    networks:
      power-net:
        ipv4_address: 10.5.0.6
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    ports:
      - "7092:7092"
      
networks:
    power-net: 
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 10.5.0.0/24