FROM golang:1.22

ADD ./ $GOPATH/src
WORKDIR $GOPATH/src

ENV GOBIN $GOPATH/bin
ENV GOSUMDB off
ENV CGO_ENABLED=0 
ENV GOOS=linux
ENV POW_DEBUG=false

ENV SERVER_ADDR=10.5.0.5:9090
ENV DIFFICULTY=1

RUN make test
RUN go build  -o $GOBIN/client ./cmd/client
CMD ["client"]