// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: v1/power.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_None           CommandType = 0
	CommandType_Connect        CommandType = 100
	CommandType_Content        CommandType = 200
	CommandType_ErrInvalidHash CommandType = 400
	CommandType_Close          CommandType = 999
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:   "None",
		100: "Connect",
		200: "Content",
		400: "ErrInvalidHash",
		999: "Close",
	}
	CommandType_value = map[string]int32{
		"None":           0,
		"Connect":        100,
		"Content":        200,
		"ErrInvalidHash": 400,
		"Close":          999,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_power_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_v1_power_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_v1_power_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command CommandType `protobuf:"varint,1,opt,name=command,proto3,enum=power.CommandType" json:"command,omitempty"`
	Body    []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_power_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_power_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_power_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_None
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_v1_power_proto protoreflect.FileDescriptor

var file_v1_power_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x2a, 0x53, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x64, 0x12, 0x0c, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x10, 0xc8, 0x01, 0x12, 0x13, 0x0a, 0x0e, 0x45, 0x72, 0x72, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x48, 0x61, 0x73, 0x68, 0x10, 0x90, 0x03, 0x12, 0x0a, 0x0a,
	0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0xe7, 0x07, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x69, 0x75, 0x63, 0x68, 0x6b, 0x6f,
	0x76, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_power_proto_rawDescOnce sync.Once
	file_v1_power_proto_rawDescData = file_v1_power_proto_rawDesc
)

func file_v1_power_proto_rawDescGZIP() []byte {
	file_v1_power_proto_rawDescOnce.Do(func() {
		file_v1_power_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_power_proto_rawDescData)
	})
	return file_v1_power_proto_rawDescData
}

var file_v1_power_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_power_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_power_proto_goTypes = []interface{}{
	(CommandType)(0), // 0: power.CommandType
	(*Message)(nil),  // 1: power.Message
}
var file_v1_power_proto_depIdxs = []int32{
	0, // 0: power.Message.command:type_name -> power.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_power_proto_init() }
func file_v1_power_proto_init() {
	if File_v1_power_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_power_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_power_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_power_proto_goTypes,
		DependencyIndexes: file_v1_power_proto_depIdxs,
		EnumInfos:         file_v1_power_proto_enumTypes,
		MessageInfos:      file_v1_power_proto_msgTypes,
	}.Build()
	File_v1_power_proto = out.File
	file_v1_power_proto_rawDesc = nil
	file_v1_power_proto_goTypes = nil
	file_v1_power_proto_depIdxs = nil
}
